
on: [push]
jobs:
  mail_on_push:
    runs_on: ubuntu-latest
    steps: 
    - name: Send Mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465 #comment
        username: ${{ secrets.MAIL_USERNAME}}
        password: ${{ secrets.MAIL_PASSWORD}}
        subject: "You've got mail!"
        body: |
                Why'd you have to go and make things so complicated?
                I see the way you're
                Actin' like you're somebody else, gets me frustrated
                Life's like this, you
                And you fall, and you crawl, and you break
                And you take what you get and you turn it into
                Honesty and promise me, I'm never gonna find you fake it
                No, no, no OKOKOK lol
        to: sandermelles@gmail.com       
        from: Github Actions
        